# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculadora_pb2 as calculadora__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in calculadora_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculadoraStub:
    """Servicio de calculadora remota expuesto mediante gRPC.

    Esta es una caracteristica anadida sobre la practica base de sockets:
    resuelve el mismo problema de fondo (invocacion remota entre un
    cliente y un servidor) pero con un mecanismo de RPC moderno en lugar
    de sockets TCP en crudo, para poder comparar ambos enfoques tal como
    se explican en el Tema 2 (Comunicacion) de la asignatura.

    El servicio expone dos modos de llamada gRPC distintos (de los cuatro
    que recogen los apuntes: unario, streaming de servidor, streaming de
    cliente y bidireccional):

    - Unario: Sumar, Restar, Multiplicar, Dividir. Una peticion, una
    respuesta. Es el caso normal, equivalente a una llamada a funcion.
    - Streaming de servidor: ObtenerHistorico. Una peticion, y el
    servidor responde con una secuencia de mensajes (uno por cada
    operacion registrada) en lugar de una unica respuesta con una
    lista dentro.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sumar = channel.unary_unary(
                '/calculadora.Calculadora/Sumar',
                request_serializer=calculadora__pb2.OperacionRequest.SerializeToString,
                response_deserializer=calculadora__pb2.OperacionResponse.FromString,
                _registered_method=True)
        self.Restar = channel.unary_unary(
                '/calculadora.Calculadora/Restar',
                request_serializer=calculadora__pb2.OperacionRequest.SerializeToString,
                response_deserializer=calculadora__pb2.OperacionResponse.FromString,
                _registered_method=True)
        self.Multiplicar = channel.unary_unary(
                '/calculadora.Calculadora/Multiplicar',
                request_serializer=calculadora__pb2.OperacionRequest.SerializeToString,
                response_deserializer=calculadora__pb2.OperacionResponse.FromString,
                _registered_method=True)
        self.Dividir = channel.unary_unary(
                '/calculadora.Calculadora/Dividir',
                request_serializer=calculadora__pb2.OperacionRequest.SerializeToString,
                response_deserializer=calculadora__pb2.OperacionResponse.FromString,
                _registered_method=True)
        self.ObtenerHistorico = channel.unary_stream(
                '/calculadora.Calculadora/ObtenerHistorico',
                request_serializer=calculadora__pb2.HistoricoRequest.SerializeToString,
                response_deserializer=calculadora__pb2.RegistroHistorico.FromString,
                _registered_method=True)


class CalculadoraServicer:
    """Servicio de calculadora remota expuesto mediante gRPC.

    Esta es una caracteristica anadida sobre la practica base de sockets:
    resuelve el mismo problema de fondo (invocacion remota entre un
    cliente y un servidor) pero con un mecanismo de RPC moderno en lugar
    de sockets TCP en crudo, para poder comparar ambos enfoques tal como
    se explican en el Tema 2 (Comunicacion) de la asignatura.

    El servicio expone dos modos de llamada gRPC distintos (de los cuatro
    que recogen los apuntes: unario, streaming de servidor, streaming de
    cliente y bidireccional):

    - Unario: Sumar, Restar, Multiplicar, Dividir. Una peticion, una
    respuesta. Es el caso normal, equivalente a una llamada a funcion.
    - Streaming de servidor: ObtenerHistorico. Una peticion, y el
    servidor responde con una secuencia de mensajes (uno por cada
    operacion registrada) en lugar de una unica respuesta con una
    lista dentro.
    """

    def Sumar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiplicar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dividir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerHistorico(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculadoraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sumar': grpc.unary_unary_rpc_method_handler(
                    servicer.Sumar,
                    request_deserializer=calculadora__pb2.OperacionRequest.FromString,
                    response_serializer=calculadora__pb2.OperacionResponse.SerializeToString,
            ),
            'Restar': grpc.unary_unary_rpc_method_handler(
                    servicer.Restar,
                    request_deserializer=calculadora__pb2.OperacionRequest.FromString,
                    response_serializer=calculadora__pb2.OperacionResponse.SerializeToString,
            ),
            'Multiplicar': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiplicar,
                    request_deserializer=calculadora__pb2.OperacionRequest.FromString,
                    response_serializer=calculadora__pb2.OperacionResponse.SerializeToString,
            ),
            'Dividir': grpc.unary_unary_rpc_method_handler(
                    servicer.Dividir,
                    request_deserializer=calculadora__pb2.OperacionRequest.FromString,
                    response_serializer=calculadora__pb2.OperacionResponse.SerializeToString,
            ),
            'ObtenerHistorico': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerHistorico,
                    request_deserializer=calculadora__pb2.HistoricoRequest.FromString,
                    response_serializer=calculadora__pb2.RegistroHistorico.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.Calculadora', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculadora.Calculadora', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calculadora:
    """Servicio de calculadora remota expuesto mediante gRPC.

    Esta es una caracteristica anadida sobre la practica base de sockets:
    resuelve el mismo problema de fondo (invocacion remota entre un
    cliente y un servidor) pero con un mecanismo de RPC moderno en lugar
    de sockets TCP en crudo, para poder comparar ambos enfoques tal como
    se explican en el Tema 2 (Comunicacion) de la asignatura.

    El servicio expone dos modos de llamada gRPC distintos (de los cuatro
    que recogen los apuntes: unario, streaming de servidor, streaming de
    cliente y bidireccional):

    - Unario: Sumar, Restar, Multiplicar, Dividir. Una peticion, una
    respuesta. Es el caso normal, equivalente a una llamada a funcion.
    - Streaming de servidor: ObtenerHistorico. Una peticion, y el
    servidor responde con una secuencia de mensajes (uno por cada
    operacion registrada) en lugar de una unica respuesta con una
    lista dentro.
    """

    @staticmethod
    def Sumar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.Calculadora/Sumar',
            calculadora__pb2.OperacionRequest.SerializeToString,
            calculadora__pb2.OperacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.Calculadora/Restar',
            calculadora__pb2.OperacionRequest.SerializeToString,
            calculadora__pb2.OperacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiplicar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.Calculadora/Multiplicar',
            calculadora__pb2.OperacionRequest.SerializeToString,
            calculadora__pb2.OperacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dividir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.Calculadora/Dividir',
            calculadora__pb2.OperacionRequest.SerializeToString,
            calculadora__pb2.OperacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerHistorico(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/calculadora.Calculadora/ObtenerHistorico',
            calculadora__pb2.HistoricoRequest.SerializeToString,
            calculadora__pb2.RegistroHistorico.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
