# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\x12\x0b\x63\x61lculadora\"(\n\x10OperacionRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"&\n\x11OperacionResponse\x12\x11\n\tresultado\x18\x01 \x01(\x01\"\x12\n\x10HistoricoRequest\"g\n\x11RegistroHistorico\x12\x11\n\toperacion\x18\x01 \x01(\t\x12\t\n\x01\x61\x18\x02 \x01(\x01\x12\t\n\x01\x62\x18\x03 \x01(\x01\x12\x11\n\tresultado\x18\x04 \x01(\x01\x12\x16\n\x0emarca_temporal\x18\x05 \x01(\t2\x8b\x03\n\x0b\x43\x61lculadora\x12\x46\n\x05Sumar\x12\x1d.calculadora.OperacionRequest\x1a\x1e.calculadora.OperacionResponse\x12G\n\x06Restar\x12\x1d.calculadora.OperacionRequest\x1a\x1e.calculadora.OperacionResponse\x12L\n\x0bMultiplicar\x12\x1d.calculadora.OperacionRequest\x1a\x1e.calculadora.OperacionResponse\x12H\n\x07\x44ividir\x12\x1d.calculadora.OperacionRequest\x1a\x1e.calculadora.OperacionResponse\x12S\n\x10ObtenerHistorico\x12\x1d.calculadora.HistoricoRequest\x1a\x1e.calculadora.RegistroHistorico0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERACIONREQUEST']._serialized_start=34
  _globals['_OPERACIONREQUEST']._serialized_end=74
  _globals['_OPERACIONRESPONSE']._serialized_start=76
  _globals['_OPERACIONRESPONSE']._serialized_end=114
  _globals['_HISTORICOREQUEST']._serialized_start=116
  _globals['_HISTORICOREQUEST']._serialized_end=134
  _globals['_REGISTROHISTORICO']._serialized_start=136
  _globals['_REGISTROHISTORICO']._serialized_end=239
  _globals['_CALCULADORA']._serialized_start=242
  _globals['_CALCULADORA']._serialized_end=637
# @@protoc_insertion_point(module_scope)
